env:
  global:
    - LC_CTYPE=en_US.UTF-8
os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.3beta
script:
  - swift build
  - swift test --parallel
notifications:
  email: false
