name: Test

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
     - uses: actions/checkout@v1
     - name: swift test
       env:
           SWIFT_VERSION: 5.1
       run: |
         eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
         swift test
